export type DropStatus = "LIVE" | "LAUNCHED" | "FAILED" | string;

export type Drop = {
  id: number;
  onchainId: number | null;
  address: string | null;
  name: string;
  symbol: string;
  description: string;
  artworkUrl: string;
  creatorHandle: string;
  creatorAddress: string;
  targetEth: number;
  raisedEth: number;
  backers: number;
  minCommitEth: number;
  creatorBps: number;
  deadline: string;
  status: DropStatus;
  tokenAddress: string | null;
  curveAddress: string | null;
  mcapUsd: number | null;
  change24h: number | null;
  liquidityUsd: number | null;
  volume24hUsd: number | null;
  holders: number | null;
  athMcapUsd: number | null;
  patronAddress: string | null;
  patronHandle: string | null;
  crownPriceEth: number | null;
  reignStart: string | null;
  reignCount: number;
  generous: boolean;
  feesEarnedEth: number;
  burnedPct: number;
  reignsJson: string;
  source: "ponsea" | "pons" | string;
  tradeUrl: string | null;
  logoUrl: string | null;
  createdAt: string;
};
